# Generated by Django 3.1.4 on 2020-12-20 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('price', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('photo', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bike_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_bike', models.CharField(max_length=15)),
                ('wheel_size', models.CharField(max_length=11)),
                ('speeds', models.PositiveSmallIntegerField()),
                ('frame', models.CharField(max_length=200)),
                ('brakes', models.CharField(max_length=100)),
                ('rudder', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=100)),
                ('footrest', models.CharField(blank=True, max_length=50)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bike_rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('region', models.CharField(max_length=40)),
                ('limit', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bike.bike')),
                ('delivery_from_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryfrombike', to='Car.delivery')),
                ('delivery_to_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Car.delivery')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.user')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bike.bike_model'),
        ),
        migrations.AddField(
            model_name='bike',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.location'),
        ),
    ]
