# Generated by Django 3.1.4 on 2020-12-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
        ('Bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.location'),
        ),
        migrations.AlterField(
            model_name='bike_rent',
            name='delivery_from_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryfrombike', to='General.delivery'),
        ),
        migrations.AlterField(
            model_name='bike_rent',
            name='delivery_to_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.delivery'),
        ),
        migrations.AlterField(
            model_name='bike_rent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.user'),
        ),
    ]
