# Generated by Django 3.1.4 on 2021-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bike', '0003_auto_20210627_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_rent',
            name='status',
            field=models.CharField(choices=[('на', 'На рассмотрении'), ('за', 'Оформлено'), ('оп', 'Оплачено'), ('во', 'Возврат средств'), ('дз', 'На доставке заказчику'), ('ак', 'Активно'), ('дл', 'На доставке в локацию'), ('вы', 'Выполнено'), ('от', 'Отменено'), ('шт', 'Ожидание оплаты штрафа')], max_length=20),
        ),
    ]
