# Generated by Django 3.1.4 on 2021-01-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_auto_20210106_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_model_id_link',
            new_name='car_model_id',
        ),
    ]
