# Generated by Django 3.1.4 on 2021-06-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_auto_20210108_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('ре', 'В ремонте'), ('св', 'Свободна'), ('ар', 'Арендована')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='status',
            field=models.CharField(choices=[('за', 'Заказано'), ('оп', 'Оплачено'), ('во', 'Возврат средств'), ('дз', 'На доставке заказчику'), ('ак', 'Активно'), ('дл', 'На доставке в локацию'), ('вы', 'Выполнено'), ('от', 'Отменено'), ('шт', 'Ожидание оплаты штрафа')], max_length=20),
        ),
    ]
