# Generated by Django 3.1.4 on 2021-06-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0006_auto_20210628_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_rent',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='end',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='start',
            field=models.CharField(max_length=16),
        ),
    ]
