# Generated by Django 3.1.4 on 2020-12-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('profile', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('metro', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rent', models.CharField(max_length=8)),
                ('delivery_location', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('price', models.PositiveSmallIntegerField()),
                ('deliveryman_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.deliveryman')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.user')),
            ],
        ),
    ]
