# Generated by Django 3.1.4 on 2021-06-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_auto_20201227_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='type_rent',
        ),
        migrations.AddField(
            model_name='delivery',
            name='type_delivery',
            field=models.CharField(default='ат', max_length=12),
            preserve_default=False,
        ),
    ]
