# Generated by Django 3.1.4 on 2021-06-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_auto_20210627_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='time',
            field=models.CharField(max_length=16),
        ),
    ]
