# Generated by Django 3.1.4 on 2021-06-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_auto_20210627_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='time',
            field=models.CharField(max_length=25),
        ),
    ]
