# Generated by Django 3.1.4 on 2021-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0010_auto_20210627_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='time',
            field=models.CharField(max_length=16),
        ),
    ]
