# Generated by Django 3.1.4 on 2021-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0011_auto_20210627_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=500),
        ),
    ]
