# Generated by Django 3.1.4 on 2021-07-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0013_auto_20210703_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='password',
            field=models.CharField(default=54321, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='54321', max_length=30),
            preserve_default=False,
        ),
    ]
