# Generated by Django 3.1.4 on 2021-07-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0014_auto_20210704_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='photo',
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
